clc
clear
%%read the data for joint 173 file
row_extracted = [1, 5, 6, 7, 11, 12, 13, 19, 20, 21, 22, 25, 36, 47, 48, 60, 61, 62, 91, 92];
titles = {
	'root', ...				%%1
	'upperleg01.L', ...		%%5
	'upperleg01.R', ...		%%6
	'spine04', ...			%%7
	'lowerleg01.L', ...		%%11
	'lowerleg01.R', ...		%%12
	'spine02', ...			%%13
	'foot.L', ...			%%19
	'foot.R', ...			%%20
	'clavicle.L', ...		%%21
	'clavicle.R', ...		%%22
	'toe2-1.L', ...			%%25
	'neck02', ...			%%36
	'upperarm01.L', ...		%%47
	'upperarm01.R', ...		%%48
	'head', ...				%%60
	'lowerarm01.L', ...		%%61
	'lowerarm01.R', ...		%%62
	'wrist.L', ...			%%91
	'wrist.R'				%%92
};

J_173_t = csvread('make_human_173.csv',0,2);
[~, t] = size(J_173_t);
n_j_173_t = length(titles);
%%read the data for joint 15 file
J_15_t = csvread('make_human_15.csv',0,2);

J_15 = J_15_t';
J_173 = J_173_t';

%%  [ root ]=>root
%%    [ pelvis.L, upperleg01.L ]=>upperleg01.L
%%      [ upperleg02.L, lowerleg01.L ]=>lowerleg01.L
%%        [ lowerleg02.L, foot.L ]=>foot.L
%%    [ pelvis.R, upperleg01.R ]=>upperleg01.R
%%      [ upperleg02.R, lowerleg01.R ]=>lowerleg01.R
%%        [ lowerleg02.R, foot.R ]=>foot.R
%%    [ spine05, spine04, spine03 ]=>spine03
%%      [ spine02, spine01, clavicle.L, shoulder01.L, upperarm01.L ]=>upperarm01.L
%%        [ upperarm02.L, lowerarm01.L ]=>lowerarm01.L
%%          [ lowerarm02.L, wrist.L ]=>wrist.L
%%      [ spine02, spine01, clavicle.R, shoulder01.R, upperarm01.R ]=>upperarm01.R
%%        [ upperarm02.R, lowerarm01.R ]=>lowerarm01.R
%%          [ lowerarm02.R, wrist.R ]=>wrist.R
%%      [ spine02, spine01, neck01 ]=>neck01

f_15_163_params = [
      1, 1;   %root=>root
      2, 5;   %upperleg01.L=>upperleg01.L
      2, 2;   %upperleg01.L=>pelvis.L
      5, 11;  %lowerleg01.L=>lowerleg01.L
      5, 8;   %lowerleg01.L=>upperleg02.L
      7, 19;  %foot.L=>foot.L
      7, 14;  %foot.L=>lowerleg02.L
      3, 6;   %upperleg01.R=>upperleg01.R
      3, 3;   %upperleg01.R=>pelvis.R
      6, 12;  %lowerleg01.R=>lowerleg01.R
      6, 9;   %lowerleg01.R=>upperleg02.R
      8, 20;  %foot.R=>foot.R
      8, 15;  %foot.R=>lowerleg02.R
      4, 10;  %spine03=>spine03
      4, 7;   %spine03=>spine04
      4, 4;   %spine03=>spine05
      10, 47; %upperarm01.L=>upperarm01.L
      10, 34; %upperarm01.L=>shoulder01.L
      10, 21; %upperarm01.L=>clavicle.L
      10, 18; %upperarm01.L=>spine01
      10, 13; %upperarm01.L=>spine02
      12, 61; %lowerarm01.L=>lowerarm01.L
      12, 58; %lowerarm01.L=>upperarm02.L
      14, 91; %wrist.L=>wrist.L
      14, 74; %wrist.L=>lowerarm02.L
      11, 48; %upperarm01.R=>upperarm01.R
      11, 35; %upperarm01.R=>shoulder01.R
      11, 22; %upperarm01.R=>clavicle.R
      11, 18; %upperarm01.R=>spine01
      11, 13; %upperarm01.R=>spine02
      13, 62; %lowerarm01.R=>lowerarm01.R
      13, 59; %lowerarm01.R=>upperarm02.R
      15, 92; %wrist.R=>wrist.R
      15, 75; %wrist.R=>lowerarm02.R
      9, 23;  %neck01=>neck01
      9, 18;  %neck01=>spine01
      9, 13   %neck01=>spine02
];

J_173_prime = J_173;
[n_parm, ~] = size(f_15_163_params);
for i_param = 1:n_parm
  i_15 = f_15_163_params(i_param, 1);
  i_173 = f_15_163_params(i_param, 2);
  J_173_prime(:, i_173) = f_i_inv(J_15(:, i_15), J_173(:, i_173), t);
end
J_173_prime_t = J_173_prime';



t = t/4;

cmp_alpha(1:n_j_173_t,1:t) = 0;
cmp_u(1:n_j_173_t,1:t) = 0;
cmp_t = 1:1:t;

r2d = 180/3.1416;
for i_r = 1:n_j_173_t
	for i_c = 1:t
        i_c2 = (i_c-1)*4+1;
        i_r2 = row_extracted(i_r);
		    q(1:4) = [J_173_t(i_r2, i_c2), J_173_t(i_r2, i_c2+1), J_173_t(i_r2, i_c2+2), J_173_t(i_r2, i_c2+3)];
		    q_prime(1:4) = [J_173_prime_t(i_r2, i_c2), J_173_prime_t(i_r2, i_c2+1), J_173_prime_t(i_r2, i_c2+2), J_173_prime_t(i_r2, i_c2+3)];
        q_alpha = acos(q(1));
        q_u(1:3) = q(2:4)/sin(q_alpha);
        q_prime_alpha = acos(q_prime(1));
        q_prime_u(1:3) = q_prime(2:4)/sin(q_prime_alpha);
        cmp_alpha(i_r, i_c) = abs(q_prime_alpha-q_alpha) * r2d;
        cmp_u(i_r, i_c) = dot(q_u, q_prime_u);
	end
end


figure
for i_g = 1:20
	subplot(10, 2, i_g)
	plot(cmp_t, cmp_alpha(i_g, :), 'r');
	title(titles(i_g));
end

figure
for i_g = 1:20
  subplot(10, 2, i_g)
  plot(cmp_t, cmp_u(i_g, :), 'r');
  title(titles(i_g));
end


names = {
	                        'root', ...
                        'pelvis.L', ...
                        'pelvis.R', ...
                         'spine05', ...
                    'upperleg01.L', ...
                    'upperleg01.R', ...
                         'spine04', ...
                    'upperleg02.L', ...
                    'upperleg02.R', ...
                         'spine03', ...
                    'lowerleg01.L', ...
                    'lowerleg01.R', ...
                         'spine02', ...
                    'lowerleg02.L', ...
                    'lowerleg02.R', ...
                        'breast.L', ...
                        'breast.R', ...
                         'spine01', ...
                          'foot.L', ...
                          'foot.R', ...
                      'clavicle.L', ...
                      'clavicle.R', ...
                          'neck01', ...
                        'toe1-1.L', ...
                        'toe2-1.L', ...
                        'toe3-1.L', ...
                        'toe4-1.L', ...
                        'toe5-1.L', ...
                        'toe1-1.R', ...
                        'toe2-1.R', ...
                        'toe3-1.R', ...
                        'toe4-1.R', ...
                        'toe5-1.R', ...
                    'shoulder01.L', ...
                    'shoulder01.R', ...
                          'neck02', ...
                        'toe1-2.L', ...
                        'toe2-2.L', ...
                        'toe3-2.L', ...
                        'toe4-2.L', ...
                        'toe5-2.L', ...
                        'toe1-2.R', ...
                        'toe2-2.R', ...
                        'toe3-2.R', ...
                        'toe4-2.R', ...
                        'toe5-2.R', ...
                    'upperarm01.L', ...
                    'upperarm01.R', ...
                          'neck03', ...
                        'toe2-3.L', ...
                        'toe3-3.L', ...
                        'toe4-3.L', ...
                        'toe5-3.L', ...
                        'toe2-3.R', ...
                        'toe3-3.R', ...
                        'toe4-3.R', ...
                        'toe5-3.R', ...
                    'upperarm02.L', ...
                    'upperarm02.R', ...
                            'head', ...
                    'lowerarm01.L', ...
                    'lowerarm01.R', ...
                             'jaw', ...
                     'levator02.L', ...
                     'levator02.R', ...
                       'special01', ...
                       'special03', ...
                     'special06.L', ...
                     'special06.R', ...
                  'temporalis01.L', ...
                  'temporalis01.R', ...
                  'temporalis02.L', ...
                  'temporalis02.R', ...
                    'lowerarm02.L', ...
                    'lowerarm02.R', ...
                       'special04', ...
                        'tongue00', ...
                     'levator03.L', ...
                     'levator03.R', ...
                        'oris04.L', ...
                        'oris04.R', ...
                          'oris06', ...
                     'levator06.L', ...
                     'levator06.R', ...
                     'special05.L', ...
                     'special05.R', ...
                       'oculi02.L', ...
                       'oculi02.R', ...
                    'risorius02.L', ...
                    'risorius02.R', ...
                         'wrist.L', ...
                         'wrist.R', ...
                          'oris02', ...
                        'oris06.L', ...
                        'oris06.R', ...
                        'tongue01', ...
                     'levator04.L', ...
                     'levator04.R', ...
                        'oris03.L', ...
                        'oris03.R', ...
                          'oris05', ...
                           'eye.L', ...
                 'orbicularis03.L', ...
                 'orbicularis04.L', ...
                           'eye.R', ...
                 'orbicularis03.R', ...
                 'orbicularis04.R', ...
                       'oculi01.L', ...
                       'oculi01.R', ...
                    'risorius03.L', ...
                    'risorius03.R', ...
                     'finger1-1.L', ...
                   'metacarpal1.L', ...
                   'metacarpal2.L', ...
                   'metacarpal3.L', ...
                   'metacarpal4.L', ...
                     'finger1-1.R', ...
                   'metacarpal1.R', ...
                   'metacarpal2.R', ...
                   'metacarpal3.R', ...
                   'metacarpal4.R', ...
                          'oris01', ...
                        'oris07.L', ...
                        'oris07.R', ...
                        'tongue02', ...
                      'tongue05.L', ...
                      'tongue05.R', ...
                     'levator05.L', ...
                     'levator05.R', ...
                     'finger1-2.L', ...
                     'finger2-1.L', ...
                     'finger3-1.L', ...
                     'finger4-1.L', ...
                     'finger5-1.L', ...
                     'finger1-2.R', ...
                     'finger2-1.R', ...
                     'finger3-1.R', ...
                     'finger4-1.R', ...
                     'finger5-1.R', ...
                        'tongue03', ...
                      'tongue06.L', ...
                      'tongue06.R', ...
                     'finger1-3.L', ...
                     'finger2-2.L', ...
                     'finger3-2.L', ...
                     'finger4-2.L', ...
                     'finger5-2.L', ...
                     'finger1-3.R', ...
                     'finger2-2.R', ...
                     'finger3-2.R', ...
                     'finger4-2.R', ...
                     'finger5-2.R', ...
                        'tongue04', ...
                      'tongue07.L', ...
                      'tongue07.R', ...
                     'finger2-3.L', ...
                     'finger3-3.L', ...
                     'finger4-3.L', ...
                     'finger5-3.L', ...
                     'finger2-3.R', ...
                     'finger3-3.R', ...
                     'finger4-3.R', ...
                     'finger5-3.R',
};

n_j = length(names);

fid = fopen('make_human_173_prime.csv', 'wt');
for i_g = 1:n_j
    name = names{i_g};
    fprintf(fid, '\n%32s', name);
    fprintf(fid, ', %8d', t);
    for i_q = 1:t
        p_q = (i_q-1)*4+1;
        w = J_173_t(i_g,p_q);
        x = J_173_t(i_g,p_q+1);
        y = J_173_t(i_g,p_q+2);
        z = J_173_t(i_g,p_q+3);
        fprintf(fid, ', %7.4f, %7.4f, %7.4f, %7.4f', w, x, y, z);
    end
end
fclose(fid);







