clc
clear
%%read the data for joint 173 file
row_extracted = [1, 5, 6, 7, 11, 12, 13, 19, 20, 21, 22, 25, 36, 47, 48, 60, 61, 62, 91, 92];
titles = {
	'root', ...				%%1
	'upperleg01.L', ...		%%5
	'upperleg01.R', ...		%%6
	'spine04', ...			%%7
	'lowerleg01.L', ...		%%11
	'lowerleg01.R', ...		%%12
	'spine02', ...			%%13
	'foot.L', ...			%%19
	'foot.R', ...			%%20
	'clavicle.L', ...		%%21
	'clavicle.R', ...		%%22
	'toe2-1.L', ...			%%25
	'neck02', ...			%%36
	'upperarm01.L', ...		%%47
	'upperarm01.R', ...		%%48
	'head', ...				%%60
	'lowerarm01.L', ...		%%61
	'lowerarm01.R', ...		%%62
	'wrist.L', ...			%%91
	'wrist.R'				%%92
};

J_173_t_raw = csvread('make_human_173.csv',0,2);
[~, t] = size(J_173_t_raw);
n_j_173_t = length(row_extracted);
%%read the data for joint 15 file
J_15_t = csvread('make_human_15.csv',0,2);
%%extract only the rotating joints from raw file
J_173_t = zeros(n_j_173_t, t);
for i_j_173_t = 1:n_j_173_t
	J_173_t(i_j_173_t, :) = J_173_t_raw(row_extracted(i_j_173_t), :);
end


J_15 = J_15_t';
[J_15_M, J_15_N] = size(J_15);


J_173 = J_173_t';

lb = zeros(J_15_N,1);
ub = ones(J_15_N, 1);
options = optimoptions('lsqlin','Algorithm','trust-region-reflective');
%%options = optimoptions(options,'SubproblemAlgorithm','factorization');
C = J_15;
f = zeros(J_15_N, n_j_173_t);
for i_f = 1:n_j_173_t
    d = J_173(:,i_f);
    f_15_163_i = lsqlin(C,d,[],[],[],[],lb,ub,[],options);
    f(:, i_f) = f_15_163_i;
end
csvwrite('f_15_163.csv', f);
J_173_prime_t = (J_15*f)';
%J_173_prime_t = J_173_t;

t = t/4;
for i_r = 1:n_j_173_t
	for i_c = 1:t
        i_c2 = (i_c-1)*4+1;
		%q_prime(1:4) = [J_173_prime_t(i_r, i_c2), J_173_prime_t(i_r, i_c2+1), J_173_prime_t(i_r, i_c2+2), J_173_prime_t(i_r, i_c2+3)];
		q_prime(1:4) = J_173_prime_t(i_r, i_c2:i_c2+3);
        q_prime = q_prime./norm(q_prime);
        J_173_prime_t(i_r, i_c2:i_c2+3) = q_prime(1:4);
	end
end

cmp_q(1:n_j_173_t,1:t) = 0;
cmp_t = 1:1:t;

for i_r = 1:n_j_173_t
	for i_c = 1:t
        i_c2 = (i_c-1)*4+1;
		q(1:4) = [J_173_t(i_r, i_c2), J_173_t(i_r, i_c2+1), J_173_t(i_r, i_c2+2), J_173_t(i_r, i_c2+3)];
		q_prime(1:4) = [J_173_prime_t(i_r, i_c2), J_173_prime_t(i_r, i_c2+1), J_173_prime_t(i_r, i_c2+2), J_173_prime_t(i_r, i_c2+3)];
        cmp_q(i_r, i_c) = abs(dot(q, q_prime));
	end
end



figure
for i_g = 1:n_j_173_t
	subplot(10, 2, i_g)
	plot(cmp_t, cmp_q(i_g, :), 'r');
	title(titles(i_g));
end

for i_j_173_t = 1:n_j_173_t
	J_173_t_raw(row_extracted(i_j_173_t), :) = J_173_prime_t(i_j_173_t, :);
end

names = {
	                        'root', ...
                        'pelvis.L', ...
                        'pelvis.R', ...
                         'spine05', ...
                    'upperleg01.L', ...
                    'upperleg01.R', ...
                         'spine04', ...
                    'upperleg02.L', ...
                    'upperleg02.R', ...
                         'spine03', ...
                    'lowerleg01.L', ...
                    'lowerleg01.R', ...
                         'spine02', ...
                    'lowerleg02.L', ...
                    'lowerleg02.R', ...
                        'breast.L', ...
                        'breast.R', ...
                         'spine01', ...
                          'foot.L', ...
                          'foot.R', ...
                      'clavicle.L', ...
                      'clavicle.R', ...
                          'neck01', ...
                        'toe1-1.L', ...
                        'toe2-1.L', ...
                        'toe3-1.L', ...
                        'toe4-1.L', ...
                        'toe5-1.L', ...
                        'toe1-1.R', ...
                        'toe2-1.R', ...
                        'toe3-1.R', ...
                        'toe4-1.R', ...
                        'toe5-1.R', ...
                    'shoulder01.L', ...
                    'shoulder01.R', ...
                          'neck02', ...
                        'toe1-2.L', ...
                        'toe2-2.L', ...
                        'toe3-2.L', ...
                        'toe4-2.L', ...
                        'toe5-2.L', ...
                        'toe1-2.R', ...
                        'toe2-2.R', ...
                        'toe3-2.R', ...
                        'toe4-2.R', ...
                        'toe5-2.R', ...
                    'upperarm01.L', ...
                    'upperarm01.R', ...
                          'neck03', ...
                        'toe2-3.L', ...
                        'toe3-3.L', ...
                        'toe4-3.L', ...
                        'toe5-3.L', ...
                        'toe2-3.R', ...
                        'toe3-3.R', ...
                        'toe4-3.R', ...
                        'toe5-3.R', ...
                    'upperarm02.L', ...
                    'upperarm02.R', ...
                            'head', ...
                    'lowerarm01.L', ...
                    'lowerarm01.R', ...
                             'jaw', ...
                     'levator02.L', ...
                     'levator02.R', ...
                       'special01', ...
                       'special03', ...
                     'special06.L', ...
                     'special06.R', ...
                  'temporalis01.L', ...
                  'temporalis01.R', ...
                  'temporalis02.L', ...
                  'temporalis02.R', ...
                    'lowerarm02.L', ...
                    'lowerarm02.R', ...
                       'special04', ...
                        'tongue00', ...
                     'levator03.L', ...
                     'levator03.R', ...
                        'oris04.L', ...
                        'oris04.R', ...
                          'oris06', ...
                     'levator06.L', ...
                     'levator06.R', ...
                     'special05.L', ...
                     'special05.R', ...
                       'oculi02.L', ...
                       'oculi02.R', ...
                    'risorius02.L', ...
                    'risorius02.R', ...
                         'wrist.L', ...
                         'wrist.R', ...
                          'oris02', ...
                        'oris06.L', ...
                        'oris06.R', ...
                        'tongue01', ...
                     'levator04.L', ...
                     'levator04.R', ...
                        'oris03.L', ...
                        'oris03.R', ...
                          'oris05', ...
                           'eye.L', ...
                 'orbicularis03.L', ...
                 'orbicularis04.L', ...
                           'eye.R', ...
                 'orbicularis03.R', ...
                 'orbicularis04.R', ...
                       'oculi01.L', ...
                       'oculi01.R', ...
                    'risorius03.L', ...
                    'risorius03.R', ...
                     'finger1-1.L', ...
                   'metacarpal1.L', ...
                   'metacarpal2.L', ...
                   'metacarpal3.L', ...
                   'metacarpal4.L', ...
                     'finger1-1.R', ...
                   'metacarpal1.R', ...
                   'metacarpal2.R', ...
                   'metacarpal3.R', ...
                   'metacarpal4.R', ...
                          'oris01', ...
                        'oris07.L', ...
                        'oris07.R', ...
                        'tongue02', ...
                      'tongue05.L', ...
                      'tongue05.R', ...
                     'levator05.L', ...
                     'levator05.R', ...
                     'finger1-2.L', ...
                     'finger2-1.L', ...
                     'finger3-1.L', ...
                     'finger4-1.L', ...
                     'finger5-1.L', ...
                     'finger1-2.R', ...
                     'finger2-1.R', ...
                     'finger3-1.R', ...
                     'finger4-1.R', ...
                     'finger5-1.R', ...
                        'tongue03', ...
                      'tongue06.L', ...
                      'tongue06.R', ...
                     'finger1-3.L', ...
                     'finger2-2.L', ...
                     'finger3-2.L', ...
                     'finger4-2.L', ...
                     'finger5-2.L', ...
                     'finger1-3.R', ...
                     'finger2-2.R', ...
                     'finger3-2.R', ...
                     'finger4-2.R', ...
                     'finger5-2.R', ...
                        'tongue04', ...
                      'tongue07.L', ...
                      'tongue07.R', ...
                     'finger2-3.L', ...
                     'finger3-3.L', ...
                     'finger4-3.L', ...
                     'finger5-3.L', ...
                     'finger2-3.R', ...
                     'finger3-3.R', ...
                     'finger4-3.R', ...
                     'finger5-3.R',
};

n_j = length(names);

fid = fopen('make_human_173_prime.csv', 'wt');
for i_g = 1:n_j
    name = names{i_g};
    fprintf(fid, '\n%32s', name);
    fprintf(fid, ', %8d', t);
    for i_q = 1:t
        p_q = (i_q-1)*4+1;
        w = J_173_t_raw(i_g,p_q);
        x = J_173_t_raw(i_g,p_q+1);
        y = J_173_t_raw(i_g,p_q+2);
        z = J_173_t_raw(i_g,p_q+3);
        fprintf(fid, ', %7.4f, %7.4f, %7.4f, %7.4f', w, x, y, z);
    end
end
fclose(fid);







